{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytidbits
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidytidbits_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytidbits/tidytidbits_{{ version }}.tar.gz
  sha256: edfcfcfe3f19f114940bafed691d6ed20c1e6b332135a14e1977caf39d5dc1f3

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-extrafont
    - r-forcats
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-dplyr
    - r-extrafont
    - r-forcats
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('tidytidbits')"           # [not win]
    - "\"%R%\" -e \"library('tidytidbits')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tidytidbits
  license: GPL-3
  summary: A selection of various tools to extend a data analysis workflow based on the 'tidyverse' packages. This includes high-level data frame editing methods
    (in the style of 'mutate'/'mutate_at'), some methods in the style of 'purrr' and 'forcats', 'lookup' methods for dict-like lists, a generic method for lumping
    a data frame by a given count, various low-level methods for special treatment of 'NA' values, 'python'-style tuple-assignment and 'truthy'/'falsy' checks, saving
    to PDF and PNG from a pipe and various small utilities.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidytidbits
# Type: Package
# Title: A Collection of Tools and Helpers Extending the Tidyverse
# Version: 0.2.1
# Author: Marcel Wiesweg [aut, cre]
# Maintainer: Marcel Wiesweg <marcel.wiesweg@uk-essen.de>
# Authors@R: person("Marcel", "Wiesweg", email = "marcel.wiesweg@uk-essen.de", role = c("aut", "cre"))
# Description: A selection of various tools to extend a data analysis workflow based on the 'tidyverse' packages. This includes high-level data frame editing methods (in the style of 'mutate'/'mutate_at'), some methods in the style of 'purrr' and 'forcats', 'lookup' methods for dict-like lists, a generic method for lumping a data frame by a given count, various low-level methods for special treatment of 'NA' values, 'python'-style tuple-assignment and 'truthy'/'falsy' checks, saving to PDF and PNG from a pipe and various small utilities.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: utils, stats, grDevices, methods, dplyr, forcats, grid, purrr, stringr, tibble, tidyr, tidyselect, extrafont, rlang, magrittr
# Suggests: survival
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-01 14:56:19 UTC; wiesweg
# Repository: CRAN
# Date/Publication: 2019-07-01 16:00:03 UTC
