appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: DzbIjxSqvRGwCp7BZLNf3C+NWoL+V2NxyICi6ZrZb1F1MsjdCHguNp/SmoxqZc7rnpCa+SP9o3WKbUpAQdW4MX43VOFHTSsqJWKNtnjyQ2O3MQR5Q0Ok2WBSS5d3CSsC830R2fk3HwkQnmrH4/AXWdr201Ydr45SumAfsUoC9nXgSZFC6bmRQJahqbnga23u9wU1AqIOut5Qvuo0jiw3uNtfv8/7/GrYCR5lTbN/imoP4Sz96J3IMQPEbpsADwou71FXHVhcKOJlX/iER2RZu8CHgdftaOaXb5thhVJIJeT09hwUQHfvcBJTb7XbikNeVLGnEgtKgZMSPuHxIlJatBHfCSncHDZ3A4hFmnWqMfM+8igq7Av+dALFD0ViIboYZ6eFWf+GMVmOrbZ4Q8zJlnqRD1jIGao8CdsuU7aVnuXtlXdifMGm4V9qZ/LiJx9YaoRpj/3zXmsPV8XGhFW+EWNTlzMXDGoAYmkq1dZ6huuDVM9Vnwkhn6TzbCz56j/1+9LwkQosSdR07UtJwvEYnI2o0gzrG8KIjsGYYCCB3p9nq5J3fqgtZox031E42n2ro3gZfJkOjtzN7BqGzT787uIUrEO7KoMcPh6/H+RWT/B/g/T91p3siNAJbw+z9N/Leobi7c7vlSBvBd9jrFpXReDmKvtFpgsiQ/WaMEJjj2w=
conda_forge_output_validation: false
